USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0"
ORIGIN = "https://login.tidal.com"
BASE_LOGIN_URI = "https://login.tidal.com"
BASE_API = "https://api.tidal.com/v2"
BASE_LISTEN_API = "https://listen.tidal.com/v1"
